-- ============================================================================
-- ISOFlow Platform - Database Schema: Tables, Primary Keys, Foreign Keys, Indexes
-- Compatible with: PostgreSQL 12+ / Azure PostgreSQL / Supabase
-- Schema Version: 3.0.0 (Multi-Tenant: organization_id on every tenant-owned table)
-- ============================================================================

-- ============================================================================
-- Drop Existing Tables (in reverse dependency order)
-- ============================================================================
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS improvements CASCADE;
DROP TABLE IF EXISTS management_decisions CASCADE;
DROP TABLE IF EXISTS management_reviews CASCADE;
DROP TABLE IF EXISTS capa_action_items CASCADE;
DROP TABLE IF EXISTS capas CASCADE;
DROP TABLE IF EXISTS findings CASCADE;
DROP TABLE IF EXISTS audits CASCADE;
DROP TABLE IF EXISTS audit_programs CASCADE;
DROP TABLE IF EXISTS evidence CASCADE;
DROP TABLE IF EXISTS task_items CASCADE;
DROP TABLE IF EXISTS task_templates CASCADE;
DROP TABLE IF EXISTS processes CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS risk_treatments CASCADE;
DROP TABLE IF EXISTS risks CASCADE;
DROP TABLE IF EXISTS controls CASCADE;
DROP TABLE IF EXISTS requirements CASCADE;
DROP TABLE IF EXISTS standards CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

-- ============================================================================
-- Create Tables & Constraints
-- ============================================================================

-- 1. Organizations Table (the tenant itself - never organization-scoped)
CREATE TABLE organizations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    industry VARCHAR(100) NOT NULL,
    employees INT NOT NULL DEFAULT 0,
    locations_json TEXT NULL,
    primary_standard VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    contact_email VARCHAR(150) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 2. Users Table (organization_id nullable - NULL = platform-level SuperAdmin)
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NULL REFERENCES organizations(id) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL DEFAULT 'Test@123',
    system_role INT NOT NULL DEFAULT 2, -- 0=SuperAdmin, 1=Admin, 2=User
    role VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    avatar_url TEXT NULL,
    phone VARCHAR(50) NULL,
    bio TEXT NULL,
    reset_token VARCHAR(50) NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 3. Standards Table (tenant-owned: each organization owns its own clause library)
CREATE TABLE standards (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    revision VARCHAR(50) NOT NULL,
    description TEXT NULL,
    requirement_count INT NOT NULL DEFAULT 0,
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    is_preseeded BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT uq_standards_org_code UNIQUE (organization_id, code)
);

-- 4. Requirements Table (tenant-owned)
CREATE TABLE requirements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    standard_id INT NOT NULL REFERENCES standards(id) ON DELETE CASCADE,
    clause VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    description TEXT NULL,
    category VARCHAR(100) NOT NULL,
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    related_control_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 5. Controls Table (tenant-owned)
CREATE TABLE controls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    requirement_id INT NULL,
    standard_id INT NULL REFERENCES standards(id) ON DELETE SET NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=NotImplemented, 1=InDevelopment, 2=Implemented, 3=Tested, 4=NeedsReview
    owner VARCHAR(150) NOT NULL,
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    is_applicable BOOLEAN NOT NULL DEFAULT TRUE,
    justification TEXT NULL,
    related_requirement_ids_json TEXT NULL,
    related_risk_ids_json TEXT NULL,
    related_treatment_ids_json TEXT NULL,
    related_policy_ids_json TEXT NULL,
    related_process_ids_json TEXT NULL,
    related_task_ids_json TEXT NULL,
    related_evidence_ids_json TEXT NULL,
    related_audit_ids_json TEXT NULL,
    related_finding_ids_json TEXT NULL,
    related_capa_ids_json TEXT NULL,
    related_management_review_ids_json TEXT NULL,
    related_improvement_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT uq_controls_org_code UNIQUE (organization_id, code)
);

-- 6. Risks Table (tenant-owned)
CREATE TABLE risks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    description TEXT NULL,
    asset VARCHAR(150) NOT NULL,
    department VARCHAR(100) NOT NULL,
    owner VARCHAR(150) NOT NULL,
    likelihood INT NOT NULL DEFAULT 1, -- 1=Rare, 2=Unlikely, 3=Possible, 4=Likely, 5=AlmostCertain
    impact INT NOT NULL DEFAULT 1,     -- 1=Negligible, 2=Minor, 3=Moderate, 4=Major, 5=Critical
    treatment_id INT NULL,
    control_id INT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Open',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT uq_risks_org_code UNIQUE (organization_id, code)
);

-- 7. Risk Treatments Table (tenant-owned)
CREATE TABLE risk_treatments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    risk_id INT NOT NULL REFERENCES risks(id) ON DELETE CASCADE,
    option VARCHAR(50) NOT NULL DEFAULT 'Mitigate',
    treatment_plan TEXT NOT NULL,
    owner VARCHAR(150) NOT NULL,
    target_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    residual_likelihood INT NOT NULL DEFAULT 1,
    residual_impact INT NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'In Progress',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 8. Policies Table (tenant-owned)
CREATE TABLE policies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    version VARCHAR(50) NOT NULL DEFAULT '1.0',
    owner VARCHAR(150) NOT NULL,
    effective_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    next_review_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    file_path VARCHAR(500) NULL,
    linked_control_ids_json TEXT NULL,
    linked_process_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT uq_policies_org_code UNIQUE (organization_id, code)
);

-- 9. Processes Table (tenant-owned)
CREATE TABLE processes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    category VARCHAR(100) NOT NULL,
    owner VARCHAR(150) NOT NULL,
    description TEXT NULL,
    version VARCHAR(50) NOT NULL DEFAULT '1.0',
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    steps_json TEXT NULL,
    policy_id INT NULL REFERENCES policies(id) ON DELETE SET NULL,
    control_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 10. Task Templates Table (tenant-owned)
CREATE TABLE task_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    description TEXT NULL,
    frequency INT NOT NULL DEFAULT 3, -- 0=Daily, 1=Weekly, 2=Fortnightly, 3=Monthly, 4=HalfYearly, 5=Yearly
    default_owner VARCHAR(150) NOT NULL,
    related_control_id INT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 11. Task Items Table (tenant-owned)
CREATE TABLE task_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    control_id INT NULL,
    risk_id INT NULL,
    owner VARCHAR(150) NOT NULL,
    priority INT NOT NULL DEFAULT 1, -- 0=Low, 1=Medium, 2=High, 3=Urgent
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INT NOT NULL DEFAULT 0,   -- 0=NotStarted, 1=InProgress, 2=Blocked, 3=Completed, 4=Overdue
    evidence_id INT NULL,
    completed_date TIMESTAMP WITHOUT TIME ZONE NULL,
    comments TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 12. Evidence Table (tenant-owned)
CREATE TABLE evidence (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(250) NOT NULL,
    type INT NOT NULL DEFAULT 0, -- 0=Document, 1=Report, 2=ApprovalRecord, 3=LogFile, 4=Screenshot, 5=PolicyDocument
    control_id INT NULL,
    requirement_id INT NULL,
    task_id INT NULL,
    audit_id INT NULL,
    uploaded_by VARCHAR(150) NOT NULL,
    upload_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Verified',
    file_url VARCHAR(500) NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 13. Audit Programs Table (tenant-owned)
CREATE TABLE audit_programs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    title VARCHAR(250) NOT NULL,
    year INT NOT NULL,
    scope TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 14. Audits Table (tenant-owned)
CREATE TABLE audits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    standard_id INT NULL REFERENCES standards(id) ON DELETE SET NULL,
    lead_auditor VARCHAR(150) NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=Planned, 1=Scheduled, 2=InProgress, 3=Reporting, 4=Completed
    completion_percentage INT NOT NULL DEFAULT 0,
    scope TEXT NULL,
    check_list_control_ids_json TEXT NULL,
    finding_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 15. Findings Table (tenant-owned)
CREATE TABLE findings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    audit_id INT NULL REFERENCES audits(id) ON DELETE SET NULL,
    requirement_id INT NULL,
    control_id INT NULL,
    severity INT NOT NULL DEFAULT 1, -- 0=OFI, 1=Observation, 2=MinorNC, 3=MajorNC
    status INT NOT NULL DEFAULT 0,   -- 0=Open, 1=InAnalysis, 2=CapaAssigned, 3=Resolved, 4=Closed
    description TEXT NULL,
    root_cause TEXT NULL,
    identified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    auditor VARCHAR(150) NOT NULL,
    capa_id INT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 16. CAPAs Table (tenant-owned)
CREATE TABLE capas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    finding_id INT NULL,
    title VARCHAR(250) NOT NULL,
    root_cause TEXT NULL,
    corrective_action TEXT NULL,
    owner VARCHAR(150) NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=Draft, 1=InAnalysis, 2=ActionPlanApproved, 3=InProgress, 4=VerificationPending, 5=Closed
    effectiveness_verification TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 17. Capa Action Items Table (tenant-owned)
CREATE TABLE capa_action_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    capa_id INT NOT NULL REFERENCES capas(id) ON DELETE CASCADE,
    title VARCHAR(250) NOT NULL,
    assigned_to VARCHAR(150) NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 18. Management Reviews Table (tenant-owned)
CREATE TABLE management_reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    period VARCHAR(50) NOT NULL DEFAULT 'Q4 2026',
    review_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    chair_person VARCHAR(150) NOT NULL,
    attendees_json TEXT NULL,
    summary TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Completed',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 19. Management Decisions Table (tenant-owned)
CREATE TABLE management_decisions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    management_review_id INT NOT NULL REFERENCES management_reviews(id) ON DELETE CASCADE,
    decision_text TEXT NOT NULL,
    owner VARCHAR(150) NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    improvement_id INT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Approved',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 20. Improvements Table (tenant-owned)
CREATE TABLE improvements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    current_state TEXT NULL,
    future_state TEXT NULL,
    source INT NOT NULL DEFAULT 0, -- 0=AuditFinding, 1=RiskAssessment, 2=Incident, 3=ManagementReview, etc.
    expected_benefit TEXT NULL,
    owner VARCHAR(150) NOT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=Identified, 1=Approved, 2=InProgress, 3=Completed, 4=Verified
    related_review_id INT NULL,
    related_finding_id INT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 21. Notifications Table (tenant-owned)
CREATE TABLE notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    title VARCHAR(250) NOT NULL,
    message TEXT NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'General',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    link_url VARCHAR(500) NULL
);

-- 22. Audit Logs Table (append-only, organization_id NULLABLE - NULL = platform-level action)
CREATE TABLE audit_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NULL REFERENCES organizations(id) ON DELETE SET NULL,
    module_name VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    performed_by VARCHAR(150) NOT NULL,
    performed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    ip_address VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    correlation_id VARCHAR(100) NULL,
    description TEXT NULL,
    old_values JSONB NULL,
    new_values JSONB NULL,
    changed_fields JSONB NULL
);

-- Append-only enforcement at the database level (defense in depth beyond "no update/delete API")
CREATE OR REPLACE FUNCTION fn_audit_logs_prevent_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only: % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_logs_prevent_update
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_audit_logs_prevent_mutation();

CREATE TRIGGER trg_audit_logs_prevent_delete
    BEFORE DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_audit_logs_prevent_mutation();

-- 23. Refresh Tokens Table (scoped transitively via user_id -> users.organization_id; no direct column)
CREATE TABLE refresh_tokens (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(256) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    replaced_by_token_hash VARCHAR(256) NULL
);

-- ============================================================================
-- Performance Indexes
-- ============================================================================
CREATE INDEX IF NOT EXISTS ix_users_org_id ON users (organization_id);
CREATE INDEX IF NOT EXISTS ix_standards_org_id ON standards (organization_id);
CREATE INDEX IF NOT EXISTS ix_requirements_org_id ON requirements (organization_id);
CREATE INDEX IF NOT EXISTS ix_requirements_standard_id ON requirements (standard_id);
CREATE INDEX IF NOT EXISTS ix_controls_org_id ON controls (organization_id);
CREATE INDEX IF NOT EXISTS ix_controls_standard_id ON controls (standard_id);
CREATE INDEX IF NOT EXISTS ix_controls_owner ON controls (owner);
CREATE INDEX IF NOT EXISTS ix_risks_org_id ON risks (organization_id);
CREATE INDEX IF NOT EXISTS ix_risks_owner ON risks (owner);
CREATE INDEX IF NOT EXISTS ix_risk_treatments_org_id ON risk_treatments (organization_id);
CREATE INDEX IF NOT EXISTS ix_risk_treatments_risk_id ON risk_treatments (risk_id);
CREATE INDEX IF NOT EXISTS ix_policies_org_id ON policies (organization_id);
CREATE INDEX IF NOT EXISTS ix_policies_owner ON policies (owner);
CREATE INDEX IF NOT EXISTS ix_processes_org_id ON processes (organization_id);
CREATE INDEX IF NOT EXISTS ix_processes_owner ON processes (owner);
CREATE INDEX IF NOT EXISTS ix_task_templates_org_id ON task_templates (organization_id);
CREATE INDEX IF NOT EXISTS ix_task_items_org_id ON task_items (organization_id);
CREATE INDEX IF NOT EXISTS ix_task_items_owner_status ON task_items (owner, status);
CREATE INDEX IF NOT EXISTS ix_evidence_org_id ON evidence (organization_id);
CREATE INDEX IF NOT EXISTS ix_evidence_control_id ON evidence (control_id);
CREATE INDEX IF NOT EXISTS ix_audit_programs_org_id ON audit_programs (organization_id);
CREATE INDEX IF NOT EXISTS ix_audits_org_id ON audits (organization_id);
CREATE INDEX IF NOT EXISTS ix_audits_standard_id ON audits (standard_id);
CREATE INDEX IF NOT EXISTS ix_findings_org_id ON findings (organization_id);
CREATE INDEX IF NOT EXISTS ix_findings_audit_id ON findings (audit_id);
CREATE INDEX IF NOT EXISTS ix_capas_org_id ON capas (organization_id);
CREATE INDEX IF NOT EXISTS ix_capas_finding_id ON capas (finding_id);
CREATE INDEX IF NOT EXISTS ix_capa_action_items_org_id ON capa_action_items (organization_id);
CREATE INDEX IF NOT EXISTS ix_management_reviews_org_id ON management_reviews (organization_id);
CREATE INDEX IF NOT EXISTS ix_management_decisions_org_id ON management_decisions (organization_id);
CREATE INDEX IF NOT EXISTS ix_improvements_org_id ON improvements (organization_id);
CREATE INDEX IF NOT EXISTS ix_improvements_owner ON improvements (owner);
CREATE INDEX IF NOT EXISTS ix_notifications_org_id ON notifications (organization_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_org_id ON audit_logs (organization_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_performed_at ON audit_logs (performed_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_module_name ON audit_logs (module_name);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity ON audit_logs (entity_name, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_performed_by ON audit_logs (performed_by);
CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_audit_logs_old_values_gin ON audit_logs USING GIN (old_values);
CREATE INDEX IF NOT EXISTS ix_audit_logs_new_values_gin ON audit_logs USING GIN (new_values);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_active ON refresh_tokens (user_id, expires_at) WHERE revoked_at IS NULL;
