-- ============================================================================
-- ISOFlow Platform - Database Schema: Tables, Primary Keys, Foreign Keys, Indexes
-- Compatible with: PostgreSQL 12+ / Azure PostgreSQL / Supabase
-- Schema Version: 2.1.0 (IST Timezone: Asia/Kolkata + Integer Keys)
-- ============================================================================

-- ============================================================================
-- Drop Existing Tables (in reverse dependency order)
-- ============================================================================
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS improvements CASCADE;
DROP TABLE IF EXISTS management_decisions CASCADE;
DROP TABLE IF EXISTS management_reviews CASCADE;
DROP TABLE IF EXISTS capa_action_items CASCADE;
DROP TABLE IF EXISTS capas CASCADE;
DROP TABLE IF EXISTS findings CASCADE;
DROP TABLE IF EXISTS audits CASCADE;
DROP TABLE IF EXISTS audit_programs CASCADE;
DROP TABLE IF EXISTS evidence CASCADE;
DROP TABLE IF EXISTS task_items CASCADE;
DROP TABLE IF EXISTS task_templates CASCADE;
DROP TABLE IF EXISTS processes CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS risk_treatments CASCADE;
DROP TABLE IF EXISTS risks CASCADE;
DROP TABLE IF EXISTS controls CASCADE;
DROP TABLE IF EXISTS requirements CASCADE;
DROP TABLE IF EXISTS standards CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

-- ============================================================================
-- Create Tables & Constraints
-- ============================================================================

-- 1. Organizations Table
CREATE TABLE organizations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    industry VARCHAR(100) NOT NULL,
    employees INT NOT NULL DEFAULT 0,
    locations_json TEXT NULL,
    primary_standard VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    contact_email VARCHAR(150) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 2. Users Table
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NULL REFERENCES organizations(id) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL DEFAULT 'Test@123',
    system_role INT NOT NULL DEFAULT 2, -- 0=SuperAdmin, 1=Admin, 2=User
    role VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500) NULL,
    phone VARCHAR(50) NULL,
    bio TEXT NULL,
    reset_token VARCHAR(50) NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 3. Standards Table
CREATE TABLE standards (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    revision VARCHAR(50) NOT NULL,
    description TEXT NULL,
    requirement_count INT NOT NULL DEFAULT 0,
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    is_preseeded BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 4. Requirements Table
CREATE TABLE requirements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_id INT NOT NULL REFERENCES standards(id) ON DELETE CASCADE,
    clause VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    description TEXT NULL,
    category VARCHAR(100) NOT NULL,
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    related_control_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 5. Controls Table
CREATE TABLE controls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(250) NOT NULL,
    requirement_id INT NULL,
    standard_id INT NULL REFERENCES standards(id) ON DELETE SET NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=NotImplemented, 1=InDevelopment, 2=Implemented, 3=Tested, 4=NeedsReview
    owner VARCHAR(150) NOT NULL,
    compliance_percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    is_applicable BOOLEAN NOT NULL DEFAULT TRUE,
    justification TEXT NULL,
    related_requirement_ids_json TEXT NULL,
    related_risk_ids_json TEXT NULL,
    related_treatment_ids_json TEXT NULL,
    related_policy_ids_json TEXT NULL,
    related_process_ids_json TEXT NULL,
    related_task_ids_json TEXT NULL,
    related_evidence_ids_json TEXT NULL,
    related_audit_ids_json TEXT NULL,
    related_finding_ids_json TEXT NULL,
    related_capa_ids_json TEXT NULL,
    related_management_review_ids_json TEXT NULL,
    related_improvement_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 6. Risks Table
CREATE TABLE risks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(250) NOT NULL,
    description TEXT NULL,
    asset VARCHAR(150) NOT NULL,
    department VARCHAR(100) NOT NULL,
    owner VARCHAR(150) NOT NULL,
    likelihood INT NOT NULL DEFAULT 1, -- 1=Rare, 2=Unlikely, 3=Possible, 4=Likely, 5=AlmostCertain
    impact INT NOT NULL DEFAULT 1,     -- 1=Negligible, 2=Minor, 3=Moderate, 4=Major, 5=Critical
    treatment_id INT NULL,
    control_id INT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Open',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 7. Risk Treatments Table
CREATE TABLE risk_treatments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id INT NOT NULL REFERENCES risks(id) ON DELETE CASCADE,
    option VARCHAR(50) NOT NULL DEFAULT 'Mitigate',
    treatment_plan TEXT NOT NULL,
    owner VARCHAR(150) NOT NULL,
    target_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    residual_likelihood INT NOT NULL DEFAULT 1,
    residual_impact INT NOT NULL DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'In Progress',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 8. Policies Table
CREATE TABLE policies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(250) NOT NULL,
    version VARCHAR(50) NOT NULL DEFAULT '1.0',
    owner VARCHAR(150) NOT NULL,
    effective_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    next_review_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    file_path VARCHAR(500) NULL,
    linked_control_ids_json TEXT NULL,
    linked_process_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 9. Processes Table
CREATE TABLE processes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(250) NOT NULL,
    category VARCHAR(100) NOT NULL,
    owner VARCHAR(150) NOT NULL,
    description TEXT NULL,
    version VARCHAR(50) NOT NULL DEFAULT '1.0',
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    steps_json TEXT NULL,
    policy_id INT NULL REFERENCES policies(id) ON DELETE SET NULL,
    control_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 10. Task Templates Table
CREATE TABLE task_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    description TEXT NULL,
    frequency VARCHAR(50) NOT NULL DEFAULT 'Quarterly',
    default_owner VARCHAR(150) NOT NULL,
    related_control_id INT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 11. Task Items Table
CREATE TABLE task_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    control_id INT NULL,
    risk_id INT NULL,
    owner VARCHAR(150) NOT NULL,
    priority INT NOT NULL DEFAULT 1, -- 0=Low, 1=Medium, 2=High, 3=Urgent
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INT NOT NULL DEFAULT 0,   -- 0=NotStarted, 1=InProgress, 2=Blocked, 3=Completed, 4=Overdue
    evidence_id INT NULL,
    completed_date TIMESTAMP WITHOUT TIME ZONE NULL,
    comments TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 12. Evidence Table
CREATE TABLE evidence (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(250) NOT NULL,
    type INT NOT NULL DEFAULT 0, -- 0=Document, 1=Report, 2=ApprovalRecord, 3=LogFile, 4=Screenshot, 5=PolicyDocument
    control_id INT NULL,
    requirement_id INT NULL,
    task_id INT NULL,
    audit_id INT NULL,
    uploaded_by VARCHAR(150) NOT NULL,
    upload_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Verified',
    file_url VARCHAR(500) NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 13. Audit Programs Table
CREATE TABLE audit_programs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    year INT NOT NULL,
    scope TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 14. Audits Table
CREATE TABLE audits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    standard_id INT NULL REFERENCES standards(id) ON DELETE SET NULL,
    lead_auditor VARCHAR(150) NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=Planned, 1=Scheduled, 2=InProgress, 3=Reporting, 4=Completed
    completion_percentage INT NOT NULL DEFAULT 0,
    scope TEXT NULL,
    check_list_control_ids_json TEXT NULL,
    finding_ids_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 15. Findings Table
CREATE TABLE findings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    audit_id INT NULL REFERENCES audits(id) ON DELETE SET NULL,
    requirement_id INT NULL,
    control_id INT NULL,
    severity INT NOT NULL DEFAULT 1, -- 0=OFI, 1=Observation, 2=MinorNC, 3=MajorNC
    status INT NOT NULL DEFAULT 0,   -- 0=Open, 1=InAnalysis, 2=CapaAssigned, 3=Resolved, 4=Closed
    description TEXT NULL,
    root_cause TEXT NULL,
    identified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    auditor VARCHAR(150) NOT NULL,
    capa_id INT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 16. CAPAs Table
CREATE TABLE capas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    finding_id INT NULL,
    title VARCHAR(250) NOT NULL,
    root_cause TEXT NULL,
    corrective_action TEXT NULL,
    owner VARCHAR(150) NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=Draft, 1=InAnalysis, 2=ActionPlanApproved, 3=InProgress, 4=VerificationPending, 5=Closed
    effectiveness_verification TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 17. Capa Action Items Table
CREATE TABLE capa_action_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capa_id INT NOT NULL REFERENCES capas(id) ON DELETE CASCADE,
    title VARCHAR(250) NOT NULL,
    assigned_to VARCHAR(150) NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 18. Management Reviews Table
CREATE TABLE management_reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    period VARCHAR(50) NOT NULL DEFAULT 'Q4 2026',
    review_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    chair_person VARCHAR(150) NOT NULL,
    attendees_json TEXT NULL,
    summary TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Completed',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 19. Management Decisions Table
CREATE TABLE management_decisions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_review_id INT NOT NULL REFERENCES management_reviews(id) ON DELETE CASCADE,
    decision_text TEXT NOT NULL,
    owner VARCHAR(150) NOT NULL,
    due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    improvement_id INT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Approved',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata')
);

-- 20. Improvements Table
CREATE TABLE improvements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    current_state TEXT NULL,
    future_state TEXT NULL,
    source INT NOT NULL DEFAULT 0, -- 0=AuditFinding, 1=RiskAssessment, 2=Incident, 3=ManagementReview, etc.
    expected_benefit TEXT NULL,
    owner VARCHAR(150) NOT NULL,
    status INT NOT NULL DEFAULT 0, -- 0=Identified, 1=Approved, 2=InProgress, 3=Completed, 4=Verified
    related_review_id INT NULL,
    related_finding_id INT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NULL
);

-- 21. Notifications Table
CREATE TABLE notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    message TEXT NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'General',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    link_url VARCHAR(500) NULL
);

-- 22. Audit Logs Table
CREATE TABLE audit_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    "user" VARCHAR(150) NOT NULL,
    action VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    entity_id VARCHAR(50) NOT NULL,
    details TEXT NULL
);

-- ============================================================================
-- Performance Indexes
-- ============================================================================
CREATE INDEX IF NOT EXISTS ix_users_org_id ON users (organization_id);
CREATE INDEX IF NOT EXISTS ix_requirements_standard_id ON requirements (standard_id);
CREATE INDEX IF NOT EXISTS ix_controls_standard_id ON controls (standard_id);
CREATE INDEX IF NOT EXISTS ix_controls_owner ON controls (owner);
CREATE INDEX IF NOT EXISTS ix_risks_owner ON risks (owner);
CREATE INDEX IF NOT EXISTS ix_risk_treatments_risk_id ON risk_treatments (risk_id);
CREATE INDEX IF NOT EXISTS ix_policies_owner ON policies (owner);
CREATE INDEX IF NOT EXISTS ix_processes_owner ON processes (owner);
CREATE INDEX IF NOT EXISTS ix_task_items_owner_status ON task_items (owner, status);
CREATE INDEX IF NOT EXISTS ix_evidence_control_id ON evidence (control_id);
CREATE INDEX IF NOT EXISTS ix_audits_standard_id ON audits (standard_id);
CREATE INDEX IF NOT EXISTS ix_findings_audit_id ON findings (audit_id);
CREATE INDEX IF NOT EXISTS ix_capas_finding_id ON capas (finding_id);
CREATE INDEX IF NOT EXISTS ix_improvements_owner ON improvements (owner);
CREATE INDEX IF NOT EXISTS ix_audit_logs_timestamp ON audit_logs ("timestamp" DESC);
