-- ============================================================================
-- ISOFlow Schema Migration: 06_Audit_Logging.sql
-- Centralized, append-only Audit Log trail for meaningful business/data changes.
-- Replaces the original write-less `audit_logs` stub from 01_Tables_And_Constraints.sql
-- (that table/function had no insert path and was never populated) with the full schema.
-- ============================================================================

DROP FUNCTION IF EXISTS sp_audit_logs_get_paged(INT, INT, VARCHAR, VARCHAR);
DROP TABLE IF EXISTS audit_logs CASCADE;

CREATE TABLE audit_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(50) NOT NULL DEFAULT '',
    module_name VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    performed_by VARCHAR(150) NOT NULL,
    performed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
    ip_address VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    correlation_id VARCHAR(100) NULL,
    description TEXT NULL,
    old_values JSONB NULL,
    new_values JSONB NULL,
    changed_fields JSONB NULL
);

CREATE INDEX ix_audit_logs_performed_at ON audit_logs (performed_at DESC);
CREATE INDEX ix_audit_logs_tenant_id ON audit_logs (tenant_id);
CREATE INDEX ix_audit_logs_module_name ON audit_logs (module_name);
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_name, entity_id);
CREATE INDEX ix_audit_logs_performed_by ON audit_logs (performed_by);
CREATE INDEX ix_audit_logs_action ON audit_logs (action);
CREATE INDEX ix_audit_logs_old_values_gin ON audit_logs USING GIN (old_values);
CREATE INDEX ix_audit_logs_new_values_gin ON audit_logs USING GIN (new_values);

-- ============================================================================
-- Append-only enforcement at the database level (defense in depth beyond "no update/delete API")
-- ============================================================================

CREATE OR REPLACE FUNCTION fn_audit_logs_prevent_mutation() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only: % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_audit_logs_prevent_update ON audit_logs;
CREATE TRIGGER trg_audit_logs_prevent_update
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_audit_logs_prevent_mutation();

DROP TRIGGER IF EXISTS trg_audit_logs_prevent_delete ON audit_logs;
CREATE TRIGGER trg_audit_logs_prevent_delete
    BEFORE DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION fn_audit_logs_prevent_mutation();

-- ============================================================================
-- Stored Procedures / Functions
-- ============================================================================

-- Single insert path. Called by AuditLogRepository only — never exposed for update/delete.
CREATE OR REPLACE FUNCTION sp_audit_logs_insert(
    p_tenant_id VARCHAR(50),
    p_module_name VARCHAR(100),
    p_entity_name VARCHAR(100),
    p_entity_id VARCHAR(50),
    p_action VARCHAR(50),
    p_performed_by VARCHAR(150),
    p_ip_address VARCHAR(64) DEFAULT NULL,
    p_user_agent VARCHAR(500) DEFAULT NULL,
    p_correlation_id VARCHAR(100) DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_old_values JSONB DEFAULT NULL,
    p_new_values JSONB DEFAULT NULL,
    p_changed_fields JSONB DEFAULT NULL
)
RETURNS INT AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO audit_logs (
        tenant_id, module_name, entity_name, entity_id, action, performed_by,
        ip_address, user_agent, correlation_id, description, old_values, new_values, changed_fields
    ) VALUES (
        p_tenant_id, p_module_name, p_entity_name, p_entity_id, p_action, p_performed_by,
        p_ip_address, p_user_agent, p_correlation_id, p_description, p_old_values, p_new_values, p_changed_fields
    )
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- Server-side paginated, multi-filter Audit Logs browser query.
CREATE OR REPLACE FUNCTION sp_audit_logs_get_paged(
    p_page_number INT,
    p_page_size INT,
    p_search_term VARCHAR(200) DEFAULT NULL,
    p_from_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    p_to_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    p_module_name VARCHAR(100) DEFAULT NULL,
    p_entity_name VARCHAR(100) DEFAULT NULL,
    p_entity_id VARCHAR(50) DEFAULT NULL,
    p_action VARCHAR(50) DEFAULT NULL,
    p_performed_by VARCHAR(150) DEFAULT NULL
)
RETURNS TABLE (
    id INT, module_name VARCHAR(100), entity_name VARCHAR(100), entity_id VARCHAR(50),
    action VARCHAR(50), performed_by VARCHAR(150), performed_at TIMESTAMP WITHOUT TIME ZONE,
    description TEXT, total_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT a.id, a.module_name, a.entity_name, a.entity_id, a.action, a.performed_by, a.performed_at,
           a.description, COUNT(*) OVER() AS total_count
    FROM audit_logs a
    WHERE (p_search_term IS NULL OR a.description ILIKE '%' || p_search_term || '%'
                                  OR a.performed_by ILIKE '%' || p_search_term || '%'
                                  OR a.entity_id ILIKE '%' || p_search_term || '%')
      AND (p_from_date IS NULL OR a.performed_at >= p_from_date)
      AND (p_to_date IS NULL OR a.performed_at <= p_to_date)
      AND (p_module_name IS NULL OR a.module_name ILIKE p_module_name)
      AND (p_entity_name IS NULL OR a.entity_name ILIKE p_entity_name)
      AND (p_entity_id IS NULL OR a.entity_id = p_entity_id)
      AND (p_action IS NULL OR a.action ILIKE p_action)
      AND (p_performed_by IS NULL OR a.performed_by ILIKE '%' || p_performed_by || '%')
    ORDER BY a.performed_at DESC
    LIMIT p_page_size OFFSET (p_page_number - 1) * p_page_size;
END;
$$ LANGUAGE plpgsql;

-- Full detail (including JSONB payloads) for the Audit Detail view.
CREATE OR REPLACE FUNCTION sp_audit_logs_get_by_id(p_id INT)
RETURNS TABLE (
    id INT, tenant_id VARCHAR(50), module_name VARCHAR(100), entity_name VARCHAR(100), entity_id VARCHAR(50),
    action VARCHAR(50), performed_by VARCHAR(150), performed_at TIMESTAMP WITHOUT TIME ZONE,
    ip_address VARCHAR(64), user_agent VARCHAR(500), correlation_id VARCHAR(100), description TEXT,
    old_values JSONB, new_values JSONB, changed_fields JSONB
) AS $$
BEGIN
    RETURN QUERY
    SELECT a.id, a.tenant_id, a.module_name, a.entity_name, a.entity_id, a.action, a.performed_by, a.performed_at,
           a.ip_address, a.user_agent, a.correlation_id, a.description, a.old_values, a.new_values, a.changed_fields
    FROM audit_logs a
    WHERE a.id = p_id;
END;
$$ LANGUAGE plpgsql;

-- Full change history for one entity, newest first — backs the "History" tab on entity detail pages.
CREATE OR REPLACE FUNCTION sp_audit_logs_get_history(p_entity_name VARCHAR(100), p_entity_id VARCHAR(50))
RETURNS TABLE (
    id INT, module_name VARCHAR(100), entity_name VARCHAR(100), entity_id VARCHAR(50),
    action VARCHAR(50), performed_by VARCHAR(150), performed_at TIMESTAMP WITHOUT TIME ZONE, description TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT a.id, a.module_name, a.entity_name, a.entity_id, a.action, a.performed_by, a.performed_at, a.description
    FROM audit_logs a
    WHERE a.entity_name ILIKE p_entity_name AND a.entity_id = p_entity_id
    ORDER BY a.performed_at DESC;
END;
$$ LANGUAGE plpgsql;
