using ISOFlow.Domain.Enums;

namespace ISOFlow.Domain.Entities;

public class Organization
{
    public string Id { get; set; } = string.Empty;
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Industry { get; set; } = string.Empty;
    public int Employees { get; set; }
    public List<string> Locations { get; set; } = new();
    public string PrimaryStandard { get; set; } = string.Empty;
    public string Status { get; set; } = "Active";
    public double CompliancePercentage { get; set; } = 85.0;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string ContactEmail { get; set; } = string.Empty;
}

public class User
{
    public string Id { get; set; } = string.Empty;
    /// <summary>Organization this user belongs to. Empty/null for SuperAdmin.</summary>
    public string OrganizationId { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    /// <summary>Plain-text mock password (all users: Test@123).</summary>
    public string Password { get; set; } = "Test@123";
    /// <summary>System-level role: SuperAdmin (global), Admin (org-scoped), User (org-scoped).</summary>
    public SystemRole SystemRole { get; set; } = SystemRole.User;
    /// <summary>Job/functional role label (e.g. Compliance Manager, CISO).</summary>
    public string Role { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public string Location { get; set; } = string.Empty;
    public string AvatarUrl { get; set; } = string.Empty;
    /// <summary>Contact phone number.</summary>
    public string Phone { get; set; } = string.Empty;
    /// <summary>Short biography shown on the profile page.</summary>
    public string Bio { get; set; } = string.Empty;
    /// <summary>8-char mock reset token generated by ForgotPassword. Null = no pending reset.</summary>
    public string? ResetToken { get; set; }
}

public class Standard
{
    public string Id { get; set; } = string.Empty;
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Revision { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public int RequirementCount { get; set; }
    public double CompliancePercentage { get; set; }
    public bool IsPreseeded { get; set; } = false;
    public string Status { get; set; } = "Active";
}

public class Requirement
{
    public string Id { get; set; } = string.Empty;
    public string StandardId { get; set; } = string.Empty;
    public string Clause { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty; // e.g. Organizational Controls, Technological Controls
    public double CompliancePercentage { get; set; }
    public List<string> RelatedControlIds { get; set; } = new();
}

public class Control
{
    public string Id { get; set; } = string.Empty; // e.g., CTRL-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string RequirementId { get; set; } = string.Empty;
    public string StandardId { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public ControlStatus Status { get; set; }
    public string Owner { get; set; } = string.Empty;
    public double CompliancePercentage { get; set; }
    public bool IsApplicable { get; set; } = true;
    public string Justification { get; set; } = string.Empty;

    // Cross-module linking IDs
    public List<string> RelatedRequirementIds { get; set; } = new();
    public List<string> RelatedRiskIds { get; set; } = new();
    public List<string> RelatedTreatmentIds { get; set; } = new();
    public List<string> RelatedPolicyIds { get; set; } = new();
    public List<string> RelatedProcessIds { get; set; } = new();
    public List<string> RelatedTaskIds { get; set; } = new();
    public List<string> RelatedEvidenceIds { get; set; } = new();
    public List<string> RelatedAuditIds { get; set; } = new();
    public List<string> RelatedFindingIds { get; set; } = new();
    public List<string> RelatedCapaIds { get; set; } = new();
    public List<string> RelatedManagementReviewIds { get; set; } = new();
    public List<string> RelatedImprovementIds { get; set; } = new();
}

public class StatementOfApplicability
{
    public string ControlId { get; set; } = string.Empty;
    public string ControlCode { get; set; } = string.Empty;
    public string ControlTitle { get; set; } = string.Empty;
    public bool Applicable { get; set; }
    public string Justification { get; set; } = string.Empty;
    public string ImplementationStatus { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public int EvidenceCount { get; set; }
}

public class Risk
{
    public string Id { get; set; } = string.Empty; // RISK-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Asset { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public RiskLikelihood Likelihood { get; set; }
    public RiskImpact Impact { get; set; }
    public int Score => (int)Likelihood * (int)Impact;
    public RiskLevel Level => Score switch
    {
        >= 15 => RiskLevel.Critical,
        >= 10 => RiskLevel.High,
        >= 5 => RiskLevel.Medium,
        _ => RiskLevel.Low
    };
    public string TreatmentId { get; set; } = string.Empty;
    public string ControlId { get; set; } = string.Empty;
    public string Status { get; set; } = "Open";
}

public class RiskTreatment
{
    public string Id { get; set; } = string.Empty; // TRT-001
    public string RiskId { get; set; } = string.Empty;
    public string Option { get; set; } = "Mitigate"; // Mitigate, Avoid, Transfer, Accept
    public string TreatmentPlan { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public DateTime TargetDate { get; set; }
    public RiskLikelihood ResidualLikelihood { get; set; }
    public RiskImpact ResidualImpact { get; set; }
    public int ResidualScore => (int)ResidualLikelihood * (int)ResidualImpact;
    public RiskLevel ResidualLevel => ResidualScore switch
    {
        >= 15 => RiskLevel.Critical,
        >= 10 => RiskLevel.High,
        >= 5 => RiskLevel.Medium,
        _ => RiskLevel.Low
    };
    public string Status { get; set; } = "In Progress";
}

public class Policy
{
    public string Id { get; set; } = string.Empty; // POL-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Version { get; set; } = "1.0";
    public string Owner { get; set; } = string.Empty;
    public DateTime EffectiveDate { get; set; }
    public DateTime NextReviewDate { get; set; }
    public string Status { get; set; } = "Active";
    public string FilePath { get; set; } = string.Empty;
    public List<string> LinkedControlIds { get; set; } = new();
    public List<string> LinkedProcessIds { get; set; } = new();
}

public class Process
{
    public string Id { get; set; } = string.Empty; // PROC-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Version { get; set; } = "1.0";
    public string Status { get; set; } = "Active";
    public List<string> Steps { get; set; } = new();
    public string PolicyId { get; set; } = string.Empty;
    public List<string> ControlIds { get; set; } = new();
}

public class TaskTemplate
{
    public string Id { get; set; } = string.Empty;
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Frequency { get; set; } = "Quarterly";
    public string DefaultOwner { get; set; } = string.Empty;
    public string RelatedControlId { get; set; } = string.Empty;
}

public class TaskItem
{
    public string Id { get; set; } = string.Empty; // TASK-2026-003
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string ControlId { get; set; } = string.Empty;
    public string RiskId { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public TaskPriority Priority { get; set; }
    public DateTime DueDate { get; set; }
    public ComplianceTaskStatus Status { get; set; }
    public string EvidenceId { get; set; } = string.Empty;
    public DateTime? CompletedDate { get; set; }
    public string Comments { get; set; } = string.Empty;
}

public class Evidence
{
    public string Id { get; set; } = string.Empty; // EVI-2026-001
    public string Code { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public EvidenceType Type { get; set; }
    public string ControlId { get; set; } = string.Empty;
    public string RequirementId { get; set; } = string.Empty;
    public string TaskId { get; set; } = string.Empty;
    public string AuditId { get; set; } = string.Empty;
    public string UploadedBy { get; set; } = string.Empty;
    public DateTime UploadDate { get; set; }
    public DateTime ExpiryDate { get; set; }
    public string Status { get; set; } = "Verified";
    public string FileUrl { get; set; } = string.Empty;
}

public class AuditProgram
{
    public string Id { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public int Year { get; set; }
    public string Scope { get; set; } = string.Empty;
    public string Status { get; set; } = "Active";
}

public class Audit
{
    public string Id { get; set; } = string.Empty; // AUD-2026-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string StandardId { get; set; } = string.Empty;
    public string LeadAuditor { get; set; } = string.Empty;
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public AuditStatus Status { get; set; }
    public int CompletionPercentage { get; set; }
    public string Scope { get; set; } = string.Empty;
    public List<string> CheckListControlIds { get; set; } = new();
    public List<string> FindingIds { get; set; } = new();
}

public class Finding
{
    public string Id { get; set; } = string.Empty; // FIND-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string AuditId { get; set; } = string.Empty;
    public string RequirementId { get; set; } = string.Empty;
    public string ControlId { get; set; } = string.Empty;
    public FindingSeverity Severity { get; set; }
    public FindingStatus Status { get; set; }
    public string Description { get; set; } = string.Empty;
    public string RootCause { get; set; } = string.Empty;
    public DateTime IdentifiedDate { get; set; }
    public string Auditor { get; set; } = string.Empty;
    public string CapaId { get; set; } = string.Empty;
}

public class CAPA
{
    public string Id { get; set; } = string.Empty; // CAPA-001
    public string Code { get; set; } = string.Empty;
    public string FindingId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string RootCause { get; set; } = string.Empty;
    public string CorrectiveAction { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public DateTime DueDate { get; set; }
    public CapaStatus Status { get; set; }
    public string EffectivenessVerification { get; set; } = string.Empty;
    public List<CapaActionItem> ActionItems { get; set; } = new();
}

public class CapaActionItem
{
    public string Id { get; set; } = string.Empty;
    public string CapaId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string AssignedTo { get; set; } = string.Empty;
    public DateTime DueDate { get; set; }
    public bool IsCompleted { get; set; }
}

public class ManagementReview
{
    public string Id { get; set; } = string.Empty; // REV-2026-Q4
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Period { get; set; } = "Q4 2026";
    public DateTime ReviewDate { get; set; }
    public string ChairPerson { get; set; } = string.Empty;
    public List<string> Attendees { get; set; } = new();
    public string Summary { get; set; } = string.Empty;
    public string Status { get; set; } = "Completed";
    public List<ManagementDecision> Decisions { get; set; } = new();
}

public class ManagementDecision
{
    public string Id { get; set; } = string.Empty;
    public string ManagementReviewId { get; set; } = string.Empty;
    public string DecisionText { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public DateTime DueDate { get; set; }
    public string ImprovementId { get; set; } = string.Empty;
    public string Status { get; set; } = "Approved";
}

public class Improvement
{
    public string Id { get; set; } = string.Empty; // IMP-001
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string CurrentState { get; set; } = string.Empty;
    public string FutureState { get; set; } = string.Empty;
    public ImprovementSource Source { get; set; }
    public string ExpectedBenefit { get; set; } = string.Empty;
    public string Owner { get; set; } = string.Empty;
    public ImprovementStatus Status { get; set; }
    public string RelatedReviewId { get; set; } = string.Empty;
    public string RelatedFindingId { get; set; } = string.Empty;
}

public class Notification
{
    public string Id { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public string Category { get; set; } = "General"; // Warning, Task, Policy, Audit
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public bool IsRead { get; set; }
    public string LinkUrl { get; set; } = string.Empty;
}

public class AuditLog
{
    public string Id { get; set; } = string.Empty;
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    public string User { get; set; } = string.Empty;
    public string Action { get; set; } = string.Empty;
    public string Module { get; set; } = string.Empty;
    public string EntityId { get; set; } = string.Empty;
    public string Details { get; set; } = string.Empty;
}
