using ISOFlow.Domain.Enums;

namespace ISOFlow.Domain.Entities;

public class User
{
    public string Id { get; set; } = string.Empty;
    /// <summary>Organization this user belongs to. Empty/null for SuperAdmin.</summary>
    public string OrganizationId { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    /// <summary>Plain-text mock password (all users: Test@123).</summary>
    public string Password { get; set; } = "Test@123";
    /// <summary>System-level role: SuperAdmin (global), Admin (org-scoped), User (org-scoped).</summary>
    public SystemRole SystemRole { get; set; } = SystemRole.User;
    /// <summary>Job/functional role label (e.g. Compliance Manager, CISO).</summary>
    public string Role { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public string Location { get; set; } = string.Empty;
    public string AvatarUrl { get; set; } = string.Empty;
    /// <summary>Contact phone number.</summary>
    public string Phone { get; set; } = string.Empty;
    /// <summary>Short biography shown on the profile page.</summary>
    public string Bio { get; set; } = string.Empty;
    /// <summary>8-char mock reset token generated by ForgotPassword. Null = no pending reset.</summary>
    public string? ResetToken { get; set; }
}
